test case events
handleFailure: anError of: aTestCase 